name: medialab

include:
  - path: network/compose.yaml
    project_directory: .
  - path: downloads/compose.yaml
    project_directory: .
  - path: arr/compose.yaml
    project_directory: .
  - path: requests/compose.yaml
    project_directory: .
  - path: dashboard/compose.yaml
    project_directory: .
  - path: setup/compose.yaml
    project_directory: .
